Task_1_2_1
fojnk/OOP pull request #12
Opened 2023-10-07 12:03 UTC by fojnk

2023-10-12 08:26 UTC, BIGNIKi requested changes

2023-10-12 08:26 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +    public void remove() {
Добавь еще метод удаления элемента, в ходе которого все дети выбранного элемента привязываются к родителю удаляемого элемента.

2023-10-18 13:31 UTC, BIGNIKi requested changes

2023-10-18 13:31 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +    public Tree<T> addChild(Tree<T> subtree) {
Хорошо бы на этот метод тоже тест написать

2023-10-18 13:31 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/Main.java
> +        BFSIterator<String> bfs = new BFSIterator<String>(tree);
Много писанины лишней: var bfs = new BFSIterator<String>(tree);

2023-10-18 13:31 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +    public Tree<T> addChild(Tree<T> subtree) {
А если сюда передали null? Хотим ли, чтобы в качестве дочерней ноды висела null? Создай свой класс исключения и кинь исключение на такую ситуацию.

2023-10-18 13:31 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +        this.childs.add(subtree);
Вижу, что поддерево добавилось, как дочернее, но почему родителя для поддерева не выставляешь? Захотим вот мы его потом удалить, а у него parent или null равен или, еще хуже, ноде, которой вообще в нашем дереве нет.

2023-10-18 13:31 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/BFSIterator.java
> +            throw new ConcurrentModificationException();
Всё-таки докрутил. Молодец

2023-10-18 13:31 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +public class Tree<T> implements Iterable<T> {
Напиши где-нибудь в коде итерирование по классу Tree через foreach. Можешь метод просто написать, который все элементы на консоль выводит. Хочу видеть, что вы понимаете, что реализовав Iterable, можно итерироваться по элементам класса через foreach.

2023-10-18 13:31 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +        return (ArrayList<Tree<T>>) childs.clone();
Ты здесь делаешь поверхностную копию. Clone, вызванный на ArrayList, просто заменит тебе ссылку на сам ArrayList, а все ссылки на элементы внутри останутся те же самые.
Тут нужно делать глубокое копирование.
Сначала реализуешь Cloneble, потом через foreach в новый лист копируешь.
Здесь пример хороший https://www.techiedelight.com/ru/construct-deep-copy-list-java/

2023-10-18 13:43 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +    public void remove() {
Старый метод удаления тоже оставь

2023-10-18 14:10 UTC, BIGNIKi requested changes

2023-10-18 14:10 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/BFSIterator.java
> +    public T next() {
next не должен просто так возвращать null, если элементы кончились.
Когда элементы кончились, он кидает исключение: NoSuchElementException
https://javarush.com/groups/posts/1884-pattern-iterator

2023-10-20 10:12 UTC, BIGNIKi requested changes

2023-10-20 10:12 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/BFSIterator.java
> +        if (this.amountOfElem != this.startedTree.getAmountOfElem()) {
А если у нас дерево долгоживущее и amountOfElem в this.startedTree переполнится, а после и вовсе снова станет равно amountOfElem?
Переделывать не обязательно, но мне будет интересно услышать идеи, как этого можно избежать.

2023-10-20 10:12 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +    public boolean equals(Tree<T> tree) {
Давай переопределять equals из Object

2023-10-20 10:12 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +    public Tree(Tree<T> tree, Tree<T> parent) {
Этот конструктор точно должен быть публичным?

2023-10-20 10:12 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/DFSIterator.java
> +    private Tree<T> startedTree;
final`ы часто не ставишь, где их можно поставить.
Я всё-таки за то, что если можем поставить, то лучше ставить, т.к. тому, кто будет читать код, сразу станет понятно, что ссылка на данный элемент нигде в коде не меняется.

2023-10-20 10:12 UTC, BIGNIKi commented on Task_1_2_1/src/test/java/org.example/MainTest.java
> +        Assertions.assertEquals(1, 1);
bruh

2023-10-20 10:21 UTC, BIGNIKi requested changes

2023-10-20 10:21 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +        var mySpliterator = Spliterators.spliterator(this.iterator(), this.amountOfElem, Spliterator.IMMUTABLE);
Можно не скупиться на характеристики для сплитератора: добавить к IMMUTABLE DISTINCT (у нас же все ноды дерева уникальны), SIZED (число элементов нам известно), NONNULL (ведь наше дерево не содержит пустые ноды). Все эти характеристики в конечном результате влияют на скорость выполнения запросов при работе с StreamAPI

2023-10-21 15:25 UTC, BIGNIKi requested changes

2023-10-21 15:25 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +            if (dfs1.next() != dfs2.next()) {
Тут ошибка. Т.к. проверяешь ссылки. А если создали два дерева разных: A -> B и A -> B? У элементов A, B из первого дерева ссылки будут отличаться от ссылок A, B из второго дерева.
Надо значения проверять.
Это говорит о том, что тесты писали плохо.

2023-10-23 17:20 UTC, fojnk commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +            if (dfs1.next() != dfs2.next()) {
Добавил тесты, вроде проверяются все же не ссылки

2023-10-25 07:23 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +            if (dfs1.next() != dfs2.next()) {
Вот тебе отличный тест, который должен возвращать true, но у тебя false. Так-что всё же проверяет ссылки
![image](https://github.com/fojnk/OOP/assets/91887896/a7ca4805-b7a1-4dc9-9d41-5bb154296821)

2023-10-25 07:37 UTC, BIGNIKi requested changes

2023-10-25 07:37 UTC, BIGNIKi commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +    public boolean equals(Object o) {
Доделать, чтобы не ссылки сравнивал

2023-10-25 14:14 UTC, fojnk commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +            if (dfs1.next() != dfs2.next()) {
<img width="418" alt="Снимок экрана 2023-10-25 в 21 13 35" src="https://github.com/fojnk/OOP/assets/109230619/7d3ed916-21aa-4718-8ef7-04ae9216ac1f">

2023-10-25 14:14 UTC, fojnk commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +            if (dfs1.next() != dfs2.next()) {
у меня он true и выводит на этом примере, ничего не менял

2023-10-25 14:21 UTC, fojnk commented on Task_1_2_1/src/main/java/org/example/Tree.java
> +            if (dfs1.next() != dfs2.next()) {
а, тут tree1 в addChild скорее всего должно было быть
<img width="391" alt="Снимок экрана 2023-10-25 в 21 20 24" src="https://github.com/fojnk/OOP/assets/109230619/53ab7c4f-9304-42c6-af77-8a4583efd167">

2023-10-26 08:54 UTC, BIGNIKi commented
На паре защтитил. Жду доп коммит на equals

2023-11-02 07:46 UTC, BIGNIKi approved these changes

2023-11-02 08:17 UTC, merged