Task_1_2_2
fojnk/OOP pull request #13
Opened 2023-10-28 11:26 UTC by fojnk

2023-11-02 08:16 UTC, BIGNIKi requested changes
На паре защитил

2023-11-02 08:16 UTC, BIGNIKi commented on Task_1_2_2/src/main/java/org/example/GraphLoader.java
> +    public static Graph<Integer> loadTxt(Integer graphType, String filename) {
Сделать тип графа через enum и через switch case

2023-11-08 08:04 UTC, BIGNIKi requested changes

2023-11-08 08:04 UTC, BIGNIKi commented on Task_1_2_2/src/main/java/org/example/Graph.java
> +        vertexes.put(key, value);
put же не обязательно меняет вершину. Если такого ключа еще не было в HashMap`е, то он добавит новую, полноценную вершину. Этот метод может сломать представление графа. + у тебя тестов на него нет

2023-11-08 08:04 UTC, BIGNIKi commented on Task_1_2_2/src/main/java/org/example/Graph.java
> +        edges.put(key, value);
Здесь тоже опасная история с put

2023-11-08 08:04 UTC, BIGNIKi commented on Task_1_2_2/src/main/java/org/example/Graph.java
> +            if (this.getEdgeById(edgeId) == e) {
Через keySet искать элемент дольше, чем возможно. У тебя get на HashMap`е в худшем случае за O(n) работает. Лучше использовать edges.entrySet(). 
Кстати, тоже не понял, зачем this.edges делаешь. this тут лишним кажется

2023-11-08 08:04 UTC, BIGNIKi commented on Task_1_2_2/src/main/java/org/example/Graph.java
> +        for (var vert : this.vertexes.values()) {
Велосипед изобрел
return vertexes.containsValue(vertex);
У hashMap`ы есть методы contains для этого (для ключа и значения)

2023-11-08 08:04 UTC, BIGNIKi commented on Task_1_2_2/src/main/java/org/example/GraphAdjacencyMatrix.java
> +        for (var vertId : this.vertexes.keySet()) {
Здесь тоже всё лучше сделать через entrySet()

2023-11-08 08:04 UTC, BIGNIKi commented on Task_1_2_2/src/main/java/org/example/GraphAdjacencyMatrix.java
> +    HashMap<Vertex<T>, HashMap<Vertex<T>, Boolean>> adjacencyMatrix;
У тебя тут не совсем матрица смежности получилась. В нормальной матрице смежности размер всегда n*n, где n - число вершин.

2023-11-08 08:04 UTC, BIGNIKi commented on Task_1_2_2/src/main/java/org/example/Graph.java
> +    public abstract HashMap<Integer, Double> dijkstra(Integer start);
Добавь еще, как по заданию, метод сортировки вершин по удалённости от заданной вершины, чтобы возвращался List вершин по удаленности от выбранной, включая выбранную (удаленность от выбранной до себя, конечно будет ноль)

2023-11-08 08:24 UTC, BIGNIKi requested changes

2023-11-08 08:24 UTC, BIGNIKi commented on Task_1_2_2/src/main/java/org/example/Edge.java
> +        this.weight = weight;
Если мы работаем, например с матрицей смежности, получим там ребро и вызовем этот метод. Что произойдет? Матрица смежности окажется в неверном состоянии. Тогда нужно этот метод переделывать.
Нельзя пользователю давать напрямую менять состояние ребра. Только через объект - Graph.

2023-11-08 16:05 UTC, fojnk commented on Task_1_2_2/src/main/java/org/example/Graph.java
> +        vertexes.put(key, value);
этот метод лишний скорее всего

2023-11-08 16:05 UTC, fojnk commented on Task_1_2_2/src/main/java/org/example/Graph.java
> +        edges.put(key, value);
этот тоже

2023-11-08 16:08 UTC, fojnk commented on Task_1_2_2/src/main/java/org/example/Edge.java
> +        this.weight = weight;
тут не понимаю как изменить ребро не затрагивая ссылки тогда, такой способ изменения веса выглядит самым безболезненным в отличие от, например, замены ребра на ребро с такими же вершинами, но другим значением, тогда все ссылки поплывут в по в некоторых представлениях графа

2023-11-16 09:22 UTC, BIGNIKi approved these changes
Сдал

2023-11-16 09:22 UTC, BIGNIKi commented on Task_1_2_2/src/main/java/org/example/GraphLoader.java
> +        Scanner scanner;
Воспользуйся try with resources

2023-11-16 14:45 UTC, closed without merging